### PR TITLE
Skip name resolve

### PR DESCRIPTION
**Pull request by grooverdan**
I didn't quite get how the online bit was done or what conditions under which it occurs however its a good way to add a settings if there is no negative impacts.

people setting grants based on reverse DNS need their heads examined anyway :-)

### CODE REVIEW

**Comment by ottok** [comment]
This does not seem to be related with getting the package to install properly, so I will review this at a later time. Getting the package installation to work flawlessly is a priority now.

**Comment by grooverdan** [comment]
agreed. need to do more that tests the 'online' path in the post install and also upgrades from previous versions.

**Comment by ottok** [comment]
Still want me to merge this?

**Comment by grooverdan** [comment]
yes

**Comment by grooverdan** [comment]
last minute thought. During mariadb-server-10.0.postinst the mysqld service isnt' actually running therefore the query of the mysql can't actually connect and therefore there can be not check.

Sorry, should of thought of this earlier.

**Comment by ottok** [comment]
Should I revert this change then?

After merging all your requests today the package is again in an uninstallable state the debug output does not at all look obvious to me:

```
+ chown -R 0:0 /usr/share/mysql
+ chown -R mysql /var/lib/mysql
+ chown -R mysql:adm /var/log/mysql
+ chmod 2750 /var/log/mysql
+ set -e
+ db_set mariadb-server/postrm_remove_database false
+ _db_cmd 'SET mariadb-server/postrm_remove_database' false
+ _db_internal_IFS=' 
'
+ IFS=' '
+ printf '%s\n' 'SET mariadb-server/postrm_remove_database false'
+ IFS=' 
'
+ IFS='
'
+ read -r _db_internal_line
debconf (developer): <-- SET mariadb-server/postrm_remove_database false
debconf (developer): --> 10 mariadb-server/postrm_remove_database doesn't exist
+ RET='10 mariadb-server/postrm_remove_database doesn'\''t exist'
+ case ${_db_internal_line%%[   ]*} in
+ return 10
+ true
+ rm -f /var/lib/mysql/debian-10.0.flag
+ touch /var/lib/mysql/debian-10.0.flag
+ set +e
+ bash /usr/bin/mysql_install_db --rpm --cross-bootstrap --user=mysql --disable-log-bin
+ logger -p daemon.err -t mysqld_safe -i
+ set -e
+ dc=/etc/mysql/debian.cnf
+ grep -sq '^\s*user\s*=\s*debian-sys-maint\s*$' /etc/mysql/debian.cnf
dpkg: error processing package mariadb-server-10.0 (--configure):
 subprocess installed post-installation script returned error exit status 2
dpkg: dependency problems prevent configuration of mariadb-server:
 mariadb-server depends on mariadb-server-10.0 (>= 10.0.17-1~exp2); however:
  Package mariadb-server-10.0 is not configured yet.

dpkg: error processing package mariadb-server (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mariadb-server-10.0
 mariadb-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by basak** [comment]
This violates Debian policy 10.7.3. For example, if a user doesn't want this then he might remove `$mysql_cfgdir/mariadb.conf.d/skip-name-resolve.cnf` and expect his change to remain after upgrades. The right way to do this kind of thing is with ucf.

**Comment by ottok** [comment]
I don't see any skip-name-resolve things in the current mariadb-server.10.0.postinst. I think this was already reverted but I cannot pin-point the commit easily. Comments @grooverdan ?

**Comment by ottok** [comment]
@basak ok, found the revert here: https://github.com/ottok/mariadb-10.0/pull/20

I've read about https://wiki.debian.org/ConfigPackages and http://man.he.net/man1/ucf but I quite don't understand where these should be implemented in the packaging, in particular now when this skip-name-resolve is reverted anyway.

**Pull request merged**
