### PR TITLE
add python dependency to package mariadb-test-data

### PR DESCRIPTION
**Pull request by ruleant**
This fixes a few Lintian errors : python-script-but-no-python-dep :
Some test scripts require python.

### CODE REVIEW

**Comment by ruleant** [comment]
https://lintian.debian.org/maintainer/pkg-mysql-maint@lists.alioth.debian.org.html#mariadb-10.0

**Comment by ottok** [comment]
Thanks for the PR! Great that you are looking at out Lintian reports.

The Lintian error might be a false positive for us, the test suite run does not normally use Python at all, those are some extra files. We need to research a bit an maybe ask @knielsen or Elena Stepanova what is appropriate here.

(Also, please use capital letters in the commit title. Write it like email subjects are written.)

**Comment by knielsen** [comment]
Hm, I've no idea why my emails randomly do or do not appear in these pull
requests pages, it's really annoying. I sent to
reply+000136c12299aa9ac69ad9c7da444cd2f8b8f3a7afdbe49b92cf000000011409d4e392a169ce0a852ab4@reply.github.com

Anyway, here is my response:

Otto Kekäläinen <notifications@github.com> writes:

> The Lintian error might be a false positive for us, the test suite run
> does not normally use Python at all, those are some extra files. We
> need to research a bit an maybe ask @knielsen or Elena Stepanova what
> is appropriate here.

So these files are from TokuDB:

    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_bin.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_bin_rename.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char_binary.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char_charbinary.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char_rename.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int_key.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int_not_supported.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int_rename.py

So I checked, and yes, this looks like a false positive. These files are
script that were used to generate the similarly named .test file for the
test suite. They are not needed to actually run the tests.

So these are source files only, and probably should not be packaged at all
(only the generated .test files are actually used when running the test
suite. So I guess the "proper" fix would be to omit these files from the
mariadb-test-data package. Or that upstream `make install` would not install
them in the first place.

If it's easy to add exceptions for package file lists (I am not sufficiently
familiar with .deb tools to know if it is), I would just omit these files
from package mysql-test-data.

But in the end, this is not an important issue I think, whatever simple fix
can be made should be good, lintian exception or whatever. Even just adding
the python dependency (as in this pull request) would not be very harmful, I
think - installing the mariadb test suite is rarely done in the first place,
and probably even more rarely done in cases where having python as well is a
problem.

Hope this helps,

 - Kristian.

**Comment by knielsen** [comment]
On Fri, 21 Oct 2016, 22:15 Kristian Nielsen, <knielsen@knielsen-hq.org>
wrote

So these are source files only, and probably should not be packaged at all
> (only the generated .test files are actually used when running the test
> suite. So I guess the "proper" fix would be to omit these files from the
> mariadb-test-data package. Or that upstream `make install` would not
> install
> them in the first place.
>

Thanks for the feedback Kristian. I'll look for a way to not have them
installed.

Kind regards,
Dieter

>

**Comment by knielsen** [comment]
Sure, I'll look into it.

**Comment by knielsen** [comment]
Otto Kekäläinen <notifications@github.com> writes:

> The Lintian error might be a false positive for us, the test suite run
> does not normally use Python at all, those are some extra files. We
> need to research a bit an maybe ask @knielsen or Elena Stepanova what
> is appropriate here.

So these files are from TokuDB:

    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_bin.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_bin_rename.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char_binary.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char_charbinary.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_char_rename.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int_key.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int_not_supported.py
    usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/change_column_int_rename.py

So I checked, and yes, this looks like a false positive. These files are
script that were used to generate the similarly named .test file for the
test suite. They are not needed to actually run the tests.

So these are source files only, and probably should not be packaged at all
(only the generated .test files are actually used when running the test
suite. So I guess the "proper" fix would be to omit these files from the
mariadb-test-data package. Or that upstream `make install` would not install
them in the first place.

If it's easy to add exceptions for package file lists (I am not sufficiently
familiar with .deb tools to know if it is), I would just omit these files
from package mysql-test-data.

But in the end, this is not an important issue I think, whatever simple fix
can be made should be good, lintian exception or whatever. Even just adding
the python dependency (as in this pull request) would not be very harmful, I
think - installing the mariadb test suite is rarely done in the first place,
and probably even more rarely done in cases where having python as well is a
problem.

Hope this helps,

 - Kristian.

**Comment by knielsen** [comment]
I guess we should either edit the mariadb-test-data.install to be more
specific and not include
usr/share/mysql/mysql-test/plugin/tokudb/tokudb/t/*.py or edit the
rules file and add to the stanza "override_dh_auto_install" that we
delete those files, so they never are included in the final package.

Dieter, would you like to give it a go?

**Comment by ottok** [comment]
I fixed this now in commit https://github.com/ottok/mariadb-10.0/commit/8deb3972ecd95892ddbb54fc75429f9b5196586a as I am about to upload 10.0.28 anyway.

**Comment by ottok** [comment]
No Lintian errors anymore at https://lintian.debian.org/maintainer/pkg-mysql-maint@lists.alioth.debian.org.html#mariadb-10.0

I also fixed the new spelling error Lintian warned about in 2b8bea6101af9db0d2de5834855b0488e2f851b2

**Pull request closed without merging**
