### PR TITLE
remove libwrap

### PR DESCRIPTION
**Pull request by grooverdan**
Libwrap is really old and uses the parsing of /etc/hosts.deny /etc/hosts.allow to determine if a connection is allowed for any tcp connection. With iptables and host based grants there is a good range of IP based access control already and this just clutters the main event loop.

### CODE REVIEW

**Comment by basak** [comment]
09:47 <rbasak> otto: incidentally I think that commit is very dangerous. Unless upstream removes support, users might expect /etc/hosts.deny to work and suddenly it won't.

09:47 <rbasak> Additionally the code will be no cleaner since support is still there (just not built).

**Comment by ottok** [comment]
@grooverdan comments?

**Comment by grooverdan** [comment]
How do you migrate away from really old choices in Debian? Its a waste of resources CPU to keep it there incurring an additional latency cost on every connection made to see if a connection makes it into a naughty/nice list based on a file or two that really only made some sense in the 80's/90s concept of system management. To a large extent I think its fortunately its a only a compile time option.

> code will be no cleaner 

WITH_LIBWRAP=NO the compiled code will be. The bit of code that processes every new connection. I can't think of a better place to start an optimisation which is why I suggested this change.

So moving on from my mini rant (I thought a request for comments was a request for a rant in Deb land :-}), how can this change be made to those who want to use mysqld like a proper 2015+ server and still satisfy be made palatable to who believe there might have archaic installations?

* We could detect /etc/hosts.{allow,deny} settings on init script and do a warning if there are user@% grants; or
* Do a separate compile to generate mysqld.libwrapper and install that in place if /etc/hosts.{allow/deny} appear to be in user and suggest they get with the times at the same time;
* A postinstall notice - "hey this has changed";

I don't think preserving it because the upstream keeps preserving it (because in turn - downstream keeps using it) leads to any real resolution or benefit to the majority of the users who don't use tcpwrappers.

**Comment by ottok** [comment]
This message indicates that upstream upstream is not anymore building with libwrap, so it would be good policy to drop it: https://lists.alioth.debian.org/pipermail/pkg-mysql-maint/2015-April/007696.html

Maybe however make some bigger notification about it just in case somebody is still using it.

**Pull request merged**
