### PR TITLE
Merging "MDEV-8692 perfschema test failures on ARM ..." from the upstream

### PR DESCRIPTION
**Pull request by abarkov**

### CODE REVIEW

**Comment by ottok** [comment]
Thanks! You could include in this adding a line in the debian/changelog. Just add that, git --amend and git push -f to this pull request so that there is one commit to merge.

**Comment by abarkov** [comment]
Thanks, added a comment into debian/changelog.

**Comment by ottok** [comment]
Thanks for the update. For the sake of learning the process, please make one small adjustment: instead of adding a new changelog section, just add your line in the currently "open" entry that has not yet been uploaded. See example in https://github.com/ottok/mariadb-10.0/commit/c84f464e717d58f49054798bb3043035372f1b38

**Comment by abarkov** [comment]
Hi Otto,


On 11/17/2015 10:33 PM, Otto Kekäläinen wrote:
> Thanks for the update. For the sake of learning the process, please make
> one small adjustment: instead of adding a new changelog section, just
> add your line in the currently "open" entry that has not yet been
> uploaded. See example in c84f464
> <https://github.com/ottok/mariadb-10.0/commit/c84f464e717d58f49054798bb3043035372f1b38>
>

Thanks. I updated the pull request.
This time I did it in a different way (also for the sake of learning).

Instead of doing "git commit --amend" followed by "git push -f",
I totally removed the commit from 
https://github.com/abarkov/mariadb-10.0/ using:

git reset HEAD^         # remove commit locally
git push origin +HEAD   # force-push the new HEAD commit

Then I pushed a new commit, and created a new pull request for the new 
commit.

It seems github can handle this properly. The old pull request 
disappeared from https://github.com/ottok/mariadb-10.0/.
There's still only one pull request from me (the new one).

Everything looks correct, doesn't it?

Greetings.

**Pull request closed without merging**
