### PR TITLE
using root with auth_socket plugin instead of debian-sys-maint

### PR DESCRIPTION
**Pull request by grooverdan**
same as 5.5 PR

### CODE REVIEW

**Comment by turagittech** [comment]
Oracle is a concept called OPS$ accounts eg OPS$mysql would allow the mySQL OS account to login to the database with what ever privileges granted to that user, no password. Often been used for batch processors in applications running against a database, this seems similar except that there is a difference that the account doesn't readily identify itself to being able to login without authentication.
Does this work along similar lines that any os user can be granted the ability to login without a password? Perhaps that is a future step, reminding the DBA that the user is logging in from that account without a password.

**Comment by grooverdan** [comment]
> Does this work along similar lines that any os user can be granted the ability to login without a password?

grant ... to '{user}'@'localhost' identified via unix_socket; with give password less access for the user where the OS username matches. The account has to be created in mysql.

> Perhaps that is a future step, reminding the DBA that the user is logging in from that account without a password.

select user from mysql.user where hostname='localhost' and 'plugin'='unix_socket'

I thought it was ok for root here as really the OS root can reset the password of mysqld (via shutting it down) so really there was no extra risk. It certainly an improvement of having debian-sys-maint user with a password in plain text that anyone can brute force eventually.

**Comment by ottok** [comment]
I merged this now. Do you Daniel come up with any reason we should *not* also clean up password related stuff at the end of the postinst script, mariadb-server-10.0.templates and mariadb-server-10.0.config?

There shouldn't be any reason to run the debconf db_input high mariadb-server/root_password or dh_get on fresh installs or upgrades, as all installations will anyway automatically start using the passwordless root unix account authentication?

**Comment by grooverdan** [comment]
nope - clean those up. I never looked at them.

right - no db_input should be needed.

**Comment by ottok** [comment]
Done in
https://github.com/ottok/mariadb-10.0/commit/a047c979ba9b6a9c4816e57f48dd2d538488e91e

**Pull request merged**
