### PR TITLE
unix_scoket via scripts/mysql_system_tables_data.sql

### PR DESCRIPTION
**Pull request by grooverdan**
rough

### CODE REVIEW

**Comment by ottok** [comment]
It would be nice to have this finalized

**Comment by ottok** [comment]
Any hope of progress on this one?

**Comment by ottok** [comment]
Asked help via https://mariadb.atlassian.net/browse/MDEV-8375

@grooverdan Can you publish your half-done simplification of the passwordless root account install that I saw you wrote in Amsterdam?

**Comment by ottok** [comment]
Suggestion from Sergei G that I'll test out now:
14:21 < serg> -INSTALL PLUGIN unix_socket SONAME 'auth_socket'; 
14:21 < serg> +INSERT plugin VALUES ('unix_socket', 'unix_socket.so');

**Comment by ottok** [comment]
Suggestion from svoj to compile directly with '-DPLUGIN_AUTH_SOCKET=STATIC'

**Comment by ottok** [comment]
Implemented in fde75c3a200d34f30d29ce8d8c89810a96466d82 and 0b74ef5750a606891df58069e1f2e24b43e9f6e9 but haven't tested i properly yet

**Comment by ottok** [comment]
Implemented and uploaded to Debian in 10.0.22-6

**Comment by grooverdan** [comment]
nice idea with builtin. I didn't think of that. Well done @ottok

**Comment by grooverdan** [comment]
FYI came across: https://github.com/dveeden/mysql-server/tree/auth_sock_flex

**Pull request closed without merging**
